[workspace]
members = ["webservice", "wasm-client", "webapp"]
resolver = "3"

[workspace.dependencies]
syn = { version = "1.0.109", features = ["derive", "parsing", "proc-macro", "full"] }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros",
    "chrono",
    "json",
    "time"
] }